// Cấu trúc 9 module + menu con. `perm` = quyền tối thiểu để thấy/ vào.
// P0 hardcode khớp seed bảng `module`; P6 sẽ nạp động từ API /modules.
export const MODULES = [
  {
    ma: 'DON_HANG',
    ten: 'Đơn hàng',
    icon: 'package',
    base: '/don-hang',
    perm: 'ORDER_VIEW',
    mau: 'bg-blue-50 text-blue-600',
    children: [
      { ten: 'Danh sách phần in vải về', route: '/don-hang/phan-in', perm: 'ORDER_VIEW' },
    ],
  },
  {
    ma: 'KY_THUAT',
    ten: 'Chuẩn bị kỹ thuật',
    icon: 'wrench',
    base: '/ky-thuat',
    perm: 'READY_VIEW',
    mau: 'bg-amber-50 text-amber-600',
    children: [
      { ten: 'Xác nhận READY', route: '/ky-thuat/ready', perm: 'READY_VIEW' },
      { ten: 'Gom set', route: '/ky-thuat/gom-set', perm: 'READY_GOMSET' },
      // Test Run - CNSP đã GỘP về màn Test Run QA (điểm 11) — bỏ menu.
    ],
  },
  {
    ma: 'KE_HOACH',
    ten: 'Kế hoạch',
    icon: 'calendar-days',
    base: '/ke-hoach',
    perm: 'RELEASE1',
    mau: 'bg-violet-50 text-violet-600',
    children: [
      { ten: 'Tạo đợt sản xuất', route: '/ke-hoach/tao-dot-san-xuat', perm: 'RELEASE1' },
      { ten: 'Kế hoạch tự động', route: '/ke-hoach/tu-dong', perm: 'RELEASE1' },
      { ten: 'Release 1', route: '/ke-hoach/release-1', perm: 'RELEASE1' },
      { ten: 'Release 2', route: '/ke-hoach/release-2', perm: 'RELEASE2' },
      { ten: 'Lập kế hoạch lại', route: '/ke-hoach/lap-lai', perm: 'RELEASE2' },
      { ten: 'Cài đặt', route: '/ke-hoach/cai-dat', perm: ['RELEASE1', 'RELEASE2'] },
    ],
  },
  {
    ma: 'SAN_XUAT',
    ten: 'Sản xuất',
    icon: 'factory',
    base: '/san-xuat',
    perm: 'PROD_MONITOR',
    mau: 'bg-emerald-50 text-emerald-600',
    children: [
      { ten: 'Xác nhận chạy', route: '/san-xuat/xac-nhan-chay', perm: 'PROD_RUN' },
      { ten: 'Theo dõi chuyền', route: '/san-xuat/theo-doi-chuyen', perm: 'PROD_MONITOR' },
      { ten: 'Tình trạng xe phơi', route: '/san-xuat/xe-phoi', perm: 'XEPHOI' },
      { ten: 'KCS', route: '/san-xuat/kcs', perm: 'KCS' },
      { ten: 'Sửa', route: '/san-xuat/sua', perm: 'SUA' },
    ],
  },
  {
    ma: 'CHAT_LUONG',
    ten: 'Chất lượng',
    icon: 'shield-check',
    base: '/chat-luong',
    perm: 'TESTRUN_QA',
    mau: 'bg-teal-50 text-teal-600',
    children: [
      { ten: 'QC chuẩn bị kỹ thuật', route: '/chat-luong/ready-qc', perm: 'READY_QC' },
      { ten: 'Test Run - QA', route: '/chat-luong/test-run', perm: 'TESTRUN_QA' },
      { ten: 'QC in line', route: '/chat-luong/qc-in-line', perm: 'QC_INLINE' },
      { ten: 'OQC', route: '/chat-luong/oqc', perm: 'OQC' },
      { ten: 'Lịch sử QC trả về', route: '/chat-luong/qc-tra-ve', perm: 'QC_TRAVE_VIEW' },
      { ten: 'Danh mục lỗi', route: '/chat-luong/danh-muc-loi', perm: 'LOI_MANAGE' },
      { ten: 'Trường hợp giao đặc biệt', route: '/chat-luong/giao-dac-biet', perm: 'GIAODB_MANAGE' },
    ],
  },
  {
    ma: 'GIAO_HANG',
    ten: 'Giao hàng',
    icon: 'truck',
    base: '/giao-hang',
    perm: 'DELIVERY_VIEW',
    mau: 'bg-orange-50 text-orange-600',
    children: [{ ten: 'Phiếu giao', route: '/giao-hang', perm: 'DELIVERY_VIEW' }],
  },
  {
    ma: 'DASHBOARD',
    ten: 'Dashboard',
    icon: 'layout-dashboard',
    base: '/dashboard',
    mau: 'bg-sky-50 text-sky-600',
    children: [
      { ten: 'Tổng quan', route: '/dashboard' },
      { ten: 'Tình trạng theo trạm', route: '/dashboard/tinh-trang-tram' },
    ],
  },
  {
    ma: 'BAO_CAO',
    ten: 'Báo cáo',
    icon: 'file-bar-chart',
    base: '/bao-cao',
    mau: 'bg-indigo-50 text-indigo-600',
    children: [
      { ten: 'Báo cáo của tôi', route: '/bao-cao', perm: 'BAOCAO_VIEW' },
      { ten: 'Báo cáo phòng ban', route: '/bao-cao/phong-ban', perm: 'BAOCAO_VIEW' },
    ],
  },
  {
    ma: 'HE_THONG',
    ten: 'Hệ thống',
    icon: 'settings',
    base: '/he-thong',
    perm: 'USER_VIEW',
    mau: 'bg-slate-100 text-slate-600',
    children: [
      { ten: 'Người dùng', route: '/he-thong/nguoi-dung', perm: 'USER_VIEW' },
      { ten: 'Vai trò', route: '/he-thong/vai-tro', perm: 'ROLE_VIEW' },
      { ten: 'Permission', route: '/he-thong/permission', perm: 'PERM_VIEW' },
      { ten: 'Module', route: '/he-thong/module', perm: 'MODULE_VIEW' },
      { ten: 'Workflow version', route: '/he-thong/workflow-version', perm: 'WORKFLOW_VIEW' },
      { ten: 'Chuyền sản xuất', route: '/he-thong/chuyen', perm: 'WORKFLOW_VIEW' },
      { ten: 'Checkpoint & Checklist', route: '/he-thong/tram-checkpoint', perm: 'WORKFLOW_VIEW' },
      { ten: 'Điều kiện chuyển checkpoint', route: '/he-thong/dieu-kien', perm: 'WORKFLOW_VIEW' },
      { ten: 'Owner checkpoint/checklist', route: '/he-thong/owner', perm: 'WORKFLOW_VIEW' },
      { ten: 'Trạng thái', route: '/he-thong/trang-thai', perm: 'STATUS_VIEW' },
      { ten: 'Hủy lệnh xác nhận', route: '/he-thong/lich-su-trang-thai', perm: ['READY_CANCEL', 'RELEASE1', 'RELEASE2', 'PROD_RUN', 'KCS', 'SUA', 'OQC'] },
      { ten: 'Đồng bộ ERP', route: '/he-thong/erp-sync', perm: 'ERP_SYNC' },
      { ten: 'Mẫu form (tem/phiếu)', route: '/he-thong/mau-form', perm: 'WORKFLOW_VIEW' },
      { ten: 'Người dùng online', route: '/he-thong/online', perm: 'PRESENCE_VIEW' },
      { ten: 'Nhật ký thao tác', route: '/he-thong/nhat-ky', perm: 'PRESENCE_VIEW' },
    ],
  },
];

export const findModuleByPath = (pathname) =>
  MODULES.find((m) => pathname === m.base || pathname.startsWith(m.base + '/')) || null;
