import {
  ArrowRight,
  Undo2,
  Redo2,
  RotateCw,
  Wifi,
  LayoutGrid,
  Copy,
  Type,
  Database,
  Package,
  Wrench,
  CalendarDays,
  Factory,
  ShieldCheck,
  Truck,
  LayoutDashboard,
  FileBarChart,
  Settings,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  LogOut,
  Search,
  User,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ChevronsUpDown,
  Bell,
  Eye,
  EyeOff,
  X,
  History,
  Users,
  Wallet,
  Printer,
  Shuffle,
  Save,
  Circle,
  Loader2,
  Play,
  Pause,
  Plus,
  Sun,
  Moon,
  Activity,
  AlertTriangle,
  Clock,
  GitBranch,
  Filter,
  CheckCircle2,
  ArrowDown,
  GripVertical,
  Download,
  FileSpreadsheet,
  ScanLine,
  QrCode,
  Barcode,
  Camera,
  Check,
  Trash2,
  Pencil,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignVerticalJustifyStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  TableCellsMerge,
  TableCellsSplit,
  WrapText,
  ZoomIn,
  ZoomOut,
  PaintBucket,
  Baseline,
  Square,
  SquareDashed,
  Rows3,
  Columns3,
  Paintbrush,
  Eraser,
  Maximize2,
  List,
} from 'lucide-react';

// Map tên kebab → component Lucide.
const MAP = {
  package: Package,
  wrench: Wrench,
  'calendar-days': CalendarDays,
  factory: Factory,
  'shield-check': ShieldCheck,
  truck: Truck,
  'layout-dashboard': LayoutDashboard,
  'file-bar-chart': FileBarChart,
  settings: Settings,
  menu: Menu,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'log-out': LogOut,
  search: Search,
  user: User,
  users: Users,
  wallet: Wallet,
  printer: Printer,
  shuffle: Shuffle,
  save: Save,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  bell: Bell,
  eye: Eye,
  'eye-off': EyeOff,
  x: X,
  close: X,
  history: History,
  loader: Loader2,
  play: Play,
  pause: Pause,
  plus: Plus,
  sun: Sun,
  moon: Moon,
  activity: Activity,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  'git-branch': GitBranch,
  filter: Filter,
  'check-circle': CheckCircle2,
  'arrow-down': ArrowDown,
  'grip-vertical': GripVertical,
  download: Download,
  'file-spreadsheet': FileSpreadsheet,
  'scan-line': ScanLine,
  'qr-code': QrCode,
  barcode: Barcode,
  camera: Camera,
  check: Check,
  'trash-2': Trash2,
  pencil: Pencil,
  // `list`: nút "Danh sách release" (Tạo đợt SX + Release 1) — trước đây chưa khai nên ra icon
  // tròn mặc định của `Icon`.
  list: List,
  // Bổ sung cho module Thiết kế tem (mig 073)
  undo: Undo2,
  redo: Redo2,
  // Mũi tên xoay TRÒN — dùng cho ô đổi phương án in ở READY (xoay vòng Bàn → Robot → Máy).
  'rotate-cw': RotateCw,
  'arrow-right': ArrowRight,
  // Nút "Thử kết nối" ở Hệ thống > Cài đặt API.
  wifi: Wifi,
  layout: LayoutGrid,
  copy: Copy,
  trash: Trash2,
  type: Type,
  database: Database,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevrons-up-down': ChevronsUpDown,
  // Thanh công cụ kiểu Excel của trình Thiết kế tem
  bold: Bold,
  italic: Italic,
  underline: Underline,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  'align-right': AlignRight,
  'align-top': AlignVerticalJustifyStart,
  'align-middle': AlignVerticalJustifyCenter,
  'align-bottom': AlignVerticalJustifyEnd,
  merge: TableCellsMerge,
  unmerge: TableCellsSplit,
  'wrap-text': WrapText,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'paint-bucket': PaintBucket,
  baseline: Baseline,
  square: Square,
  'square-dashed': SquareDashed,
  rows: Rows3,
  columns: Columns3,
  paintbrush: Paintbrush,
  eraser: Eraser,
  'maximize-2': Maximize2,
};

export default function Icon({ name, size = 20, className = '' }) {
  const Cmp = MAP[name] || Circle;
  return <Cmp size={size} className={className} aria-hidden="true" />;
}
