import {
  Package,
  Wrench,
  CalendarDays,
  Factory,
  ShieldCheck,
  Truck,
  LayoutDashboard,
  FileBarChart,
  Settings,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  LogOut,
  Search,
  User,
  ChevronRight,
  ChevronLeft,
  Bell,
  Eye,
  EyeOff,
  X,
  History,
  Users,
  Wallet,
  Printer,
  Circle,
  Loader2,
  Play,
  Pause,
  Plus,
  Sun,
  Moon,
  Activity,
  AlertTriangle,
  Clock,
  GitBranch,
  Filter,
  CheckCircle2,
  ArrowDown,
  GripVertical,
  Download,
  FileSpreadsheet,
} from 'lucide-react';

// Map tên kebab → component Lucide.
const MAP = {
  package: Package,
  wrench: Wrench,
  'calendar-days': CalendarDays,
  factory: Factory,
  'shield-check': ShieldCheck,
  truck: Truck,
  'layout-dashboard': LayoutDashboard,
  'file-bar-chart': FileBarChart,
  settings: Settings,
  menu: Menu,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'log-out': LogOut,
  search: Search,
  user: User,
  users: Users,
  wallet: Wallet,
  printer: Printer,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  bell: Bell,
  eye: Eye,
  'eye-off': EyeOff,
  x: X,
  close: X,
  history: History,
  loader: Loader2,
  play: Play,
  pause: Pause,
  plus: Plus,
  sun: Sun,
  moon: Moon,
  activity: Activity,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  'git-branch': GitBranch,
  filter: Filter,
  'check-circle': CheckCircle2,
  'arrow-down': ArrowDown,
  'grip-vertical': GripVertical,
  download: Download,
  'file-spreadsheet': FileSpreadsheet,
};

export default function Icon({ name, size = 20, className = '' }) {
  const Cmp = MAP[name] || Circle;
  return <Cmp size={size} className={className} aria-hidden="true" />;
}
